version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./public:/var/www/html/public
      - ./storage:/var/www/html/storage
      - ./bootstrap:/var/www/html/bootstrap
    ports:
      - "8008:80"
    networks:
      - laravel_network
    depends_on:
      - db
      - selenium-hub

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: projet_docker
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  db_test:
    image: mysql:8.0
    container_name: laravel_db_test
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: projet_docker_test
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata_test:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - db
    networks:
      - laravel_network

  selenium-hub:
    image: selenium/hub:4.11.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - laravel_network

  chrome:
    image: selenium/node-chrome:4.11.0
    container_name: chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - laravel_network

volumes:
  dbdata:
  dbdata_test:

networks:
  laravel_network:
    driver: bridge